"""Symbolic constants for some hard-to-type characters."""

RSQUO = '\N{RIGHT SINGLE QUOTATION MARK}'

LDQUO = '\N{LEFT DOUBLE QUOTATION MARK}'

RDQUO = '\N{RIGHT DOUBLE QUOTATION MARK}'

HELLIP = '\N{HORIZONTAL ELLIPSIS}'

TIMES = '\N{MULTIPLICATION SIGN}'
