#!/usr/bin/env python3

import argparse
import math
import os
import sys

from PySide6.QtCore import Qt
from PySide6.QtGui import QPixmap, QResizeEvent
from PySide6.QtWidgets import (QApplication,
                               QFileDialog,
                               QLabel,
                               QMenu,
                               QMessageBox)

from widgets import ResizedNotifyingWidget

APP_NAME = 'Image Viewer'
MAX_START_RATIO = 0.9

RSQUO = '\N{RIGHT SINGLE QUOTATION MARK}'
LDQUO = '\N{LEFT DOUBLE QUOTATION MARK}'
RDQUO = '\N{RIGHT DOUBLE QUOTATION MARK}'
HELLIP = '\N{HORIZONTAL ELLIPSIS}'

parser = argparse.ArgumentParser(APP_NAME)
parser.add_argument('path',
                    nargs='?',
                    help='The path of the image to be opened.',
                    type=str)
path = parser.parse_args().path

print(f'{sys.argv[0]}: PID {os.getpid()}', file=sys.stderr)

app = QApplication(sys.argv)
window = ResizedNotifyingWidget()
screenBounds = window.screen().geometry()
maxWidth = math.floor(screenBounds.width() * MAX_START_RATIO)
maxHeight = math.floor(screenBounds.height() * MAX_START_RATIO)

if path is None:
    path, _ = QFileDialog.getOpenFileName(window,
                                          'Open Image File',
                                          os.path.expanduser('~'))
    if not path:
        sys.exit(1)  # If the user cancels out of the dialog, just quit.

picture = QPixmap(path)

if picture.isNull():
    dialog = QMessageBox()
    dialog.setWindowTitle(APP_NAME)
    dialog.setText(f'Couldn{RSQUO}t open {LDQUO}{path}{RDQUO}')
    dialog.setIcon(QMessageBox.Critical)
    dialog.setWindowFlag(Qt.WindowStaysOnTopHint)
    dialog.exec_()
    sys.exit(1)

def showAbout():
    QMessageBox.about(window,
                      f'About {APP_NAME}',
                      'Image Viewer is an image viewer by Eliah Kagan.')

menu = QMenu(window)
menu.addAction(f'About{HELLIP}', showAbout)
menu.addAction(f'About Qt{HELLIP}', lambda: QMessageBox.aboutQt(window))

def showMenu(pos):
    return menu.exec_(window.mapToGlobal(pos))

label = QLabel(window)
label.setScaledContents(True)
label.setPixmap(picture)
label.setContextMenuPolicy(Qt.CustomContextMenu)
label.customContextMenuRequested.connect(showMenu)

def handleResize(event: QResizeEvent):
    ratio = min(event.size().width() / picture.width(),
                event.size().height() / picture.height())

    width = picture.width() * ratio
    height = picture.height() * ratio
    x = max(0, math.floor((event.size().width() - width) / 2))
    y = max(0, math.floor((event.size().height() - height) / 2))
    label.setGeometry(x, y, math.ceil(width), math.ceil(height))

window.setWindowTitle(f'{APP_NAME} - {os.path.basename(path)}')
window.resized.connect(handleResize)

initialRatio = min(1.0,
                   maxWidth / picture.width(),
                   maxHeight / picture.height())
initialWidth = math.ceil(picture.width() * initialRatio)
initialHeight = math.ceil(picture.height() * initialRatio)
window.resize(initialWidth, initialHeight)

window.show()
sys.exit(app.exec_())
